export type AnalysisLanguage = 'en' | 'pt' | 'es';

const messages = {
  en: {
    req_username_presence: 'Username presence',
    req_account_correlation: 'Public account correlation',
    req_digital_footprint: 'Digital footprint mapping',
    req_developer_footprint: 'Developer footprint',
    req_threat_research_alias: 'Threat research alias mapping',
    req_brand_impersonation: 'Brand impersonation monitoring',
    evidence_direct: 'The public profile exposes an independent outbound link, which can corroborate the finding beyond handle reuse.',
    evidence_lead: 'The public presence is a lead. It requires independent corroboration before any identity conclusion.',
    evidence_inconclusive: 'The endpoint is inconclusive and should not be used as positive identity evidence.',
    pivot_direct: 'Validate the self-declared public link and compare whether the same public identifier appears independently elsewhere.',
    pivot_metadata: 'Compare public metadata and independent self-declared links before correlating this profile with another account.',
    contradiction_display: 'Public display names differ across observed profiles.',
    contradiction_location: 'Public location fields differ across observed profiles.',
    contradiction_org: 'Public organization fields differ across observed profiles.',
    contradiction_avatar: 'Public avatar hashes differ across observed profiles; visual identity correlation should be reduced until independently resolved.',
    contradiction_weak: '{count} positive result(s) rely on weak detector or observation confidence.',
    judgment_high: '{count} high-value public finding(s) are relevant to {requirement}.',
    judgment_none: 'No high-value finding currently supports a strong analytical conclusion.',
    judgment_basis: 'Effective coverage {coverage}%; {count} high-value finding(s).',
    judgment_cluster: '{category} is the strongest observed footprint cluster.',
    judgment_cluster_basis: '{count} findings; weighted score {score}/100.',
    judgment_gap: 'Collection gaps materially limit negative conclusions.',
    judgment_gap_basis: '{count} result(s) are uncertain, rate-limited or errored.',
    gap1_q: 'What conclusions would change if currently inconclusive services became available?',
    gap1_r: 'Only {coverage}% of requested collection is conclusive.',
    gap2_q: 'Is there an independent public cross-link connecting two or more findings?',
    gap2_r: 'Handle reuse alone is insufficient for strong cross-account correlation.',
    gap3_q: 'Can any finding be upgraded with a stronger public source?',
    gap3_r: 'The current evidence set lacks high-quality source grades.',
    pivot_contradiction_signal: '{count} contradictory signal(s)',
    pivot_contradiction_action: 'Resolve contradictory public metadata before increasing correlation confidence.',
    pivot_contradiction_reason: 'Contradictory evidence can invalidate an otherwise plausible account-correlation hypothesis.',
    pivot_collection_signal: '{count} inconclusive protected response(s)',
    pivot_collection_action: 'Re-run only inconclusive detectors later with conservative concurrency.',
    pivot_collection_reason: 'Targeted retry is more efficient and less noisy than repeating the full scan.',
    timeline_found: 'Public profile signal observed during this scan.',
    timeline_uncertain: 'Inconclusive observation during this scan.',
    timeline_created: 'Public account-creation timestamp reported by the source.',
    timeline_first: 'First public evidence timestamp recorded for this profile.',
    timeline_source: 'Source-specific observation timestamp.',
    hypothesis_h1: 'A subset of high-confidence findings may represent the same public online identity.',
    hypothesis_h1_caveat: 'Same handle is only a lead; independent public corroboration is required.',
    hypothesis_h2: 'Findings inside the {category} cluster may be more strongly related to each other than to findings in other clusters.',
    hypothesis_h2_caveat: 'Cluster similarity reflects observable service context, not a claim about private identity.',
    hypothesis_h3: 'Some lower-confidence findings may be unrelated username collisions.',
    hypothesis_h3_caveat: 'This is the explicit alternative hypothesis and should remain open until independent corroboration exists.',
    known_presence: '{platform}: public presence observed at {url}',
    plan1: 'Validate self-declared public links from the highest-priority findings.',
    plan2: 'Resolve contradictory public metadata before raising correlation confidence.',
    plan3: 'Re-run only inconclusive detectors after a cooldown when collection coverage materially affects the assessment.',
    plan4: 'Stop broadening collection when new evidence no longer changes key judgments or closes an identified intelligence gap.',
    stop: 'Stop expanding collection when new public evidence no longer materially changes the key judgments, resolves a contradiction, or closes an identified intelligence gap.',
    sourceA: 'A = direct/stable public evidence with strong detector and observation support.',
    sourceB: 'B = strong public platform evidence.',
    sourceC: 'C = usable evidence that still requires corroboration.',
    sourceD: 'D = weak or inconclusive observation.',
    sourceE: 'E = unverified or structurally weak signal.',
    sourceAI: 'AI synthesis cannot independently raise factual confidence.',
  },
  pt: {
    req_username_presence: 'Presença de username',
    req_account_correlation: 'Correlação pública de contas',
    req_digital_footprint: 'Mapeamento de pegada digital',
    req_developer_footprint: 'Pegada de desenvolvimento',
    req_threat_research_alias: 'Mapeamento de alias para pesquisa de ameaças',
    req_brand_impersonation: 'Monitoramento de personificação de marca',
    evidence_direct: 'O perfil público expõe um link de saída independente, que pode corroborar o achado além da reutilização do username.',
    evidence_lead: 'A presença pública é um lead. Ela exige corroboração independente antes de qualquer conclusão de identidade.',
    evidence_inconclusive: 'O endpoint é inconclusivo e não deve ser usado como evidência positiva de identidade.',
    pivot_direct: 'Valide o link público autodeclarado e compare se o mesmo identificador público aparece de forma independente em outro lugar.',
    pivot_metadata: 'Compare metadados públicos e links autodeclarados independentes antes de correlacionar este perfil com outra conta.',
    contradiction_display: 'Os nomes públicos exibidos diferem entre os perfis observados.',
    contradiction_location: 'Os campos públicos de localização diferem entre os perfis observados.',
    contradiction_org: 'Os campos públicos de organização diferem entre os perfis observados.',
    contradiction_avatar: 'Os hashes públicos de avatar diferem entre os perfis observados; a correlação visual de identidade deve ser reduzida até resolução independente.',
    contradiction_weak: '{count} resultado(s) positivo(s) dependem de detector ou observação de baixa confiança.',
    judgment_high: '{count} achado(s) público(s) de alto valor são relevantes para {requirement}.',
    judgment_none: 'Nenhum achado de alto valor sustenta atualmente uma conclusão analítica forte.',
    judgment_basis: 'Cobertura efetiva {coverage}%; {count} achado(s) de alto valor.',
    judgment_cluster: '{category} é o cluster de pegada observado mais forte.',
    judgment_cluster_basis: '{count} achados; score ponderado {score}/100.',
    judgment_gap: 'Lacunas de coleta limitam materialmente conclusões negativas.',
    judgment_gap_basis: '{count} resultado(s) estão incertos, rate-limited ou com erro.',
    gap1_q: 'Que conclusões mudariam se os serviços atualmente inconclusivos se tornassem disponíveis?',
    gap1_r: 'Apenas {coverage}% da coleta solicitada é conclusiva.',
    gap2_q: 'Existe um cross-link público independente conectando dois ou mais achados?',
    gap2_r: 'A reutilização do mesmo username, sozinha, é insuficiente para correlação forte entre contas.',
    gap3_q: 'Algum achado pode ser elevado com uma fonte pública mais forte?',
    gap3_r: 'O conjunto atual de evidências não possui fontes de alta qualidade suficientes.',
    pivot_contradiction_signal: '{count} sinal(is) contraditório(s)',
    pivot_contradiction_action: 'Resolva metadados públicos contraditórios antes de aumentar a confiança de correlação.',
    pivot_contradiction_reason: 'Evidência contraditória pode invalidar uma hipótese de correlação de contas aparentemente plausível.',
    pivot_collection_signal: '{count} resposta(s) protegida(s) inconclusiva(s)',
    pivot_collection_action: 'Execute novamente apenas os detectores inconclusivos depois, com concorrência conservadora.',
    pivot_collection_reason: 'Uma nova tentativa direcionada é mais eficiente e menos ruidosa do que repetir o scan completo.',
    timeline_found: 'Sinal de perfil público observado durante este scan.',
    timeline_uncertain: 'Observação inconclusiva durante este scan.',
    timeline_created: 'Timestamp público de criação da conta informado pela fonte.',
    timeline_first: 'Timestamp da primeira evidência pública registrado para este perfil.',
    timeline_source: 'Timestamp específico de observação informado pela fonte.',
    hypothesis_h1: 'Um subconjunto de achados de alta confiança pode representar a mesma identidade pública online.',
    hypothesis_h1_caveat: 'Mesmo username é apenas um lead; corroboração pública independente é necessária.',
    hypothesis_h2: 'Achados dentro do cluster {category} podem estar mais relacionados entre si do que com achados de outros clusters.',
    hypothesis_h2_caveat: 'Similaridade de cluster reflete contexto observável de serviço, não uma afirmação sobre identidade privada.',
    hypothesis_h3: 'Alguns achados de menor confiança podem ser colisões de username sem relação entre si.',
    hypothesis_h3_caveat: 'Esta é a hipótese alternativa explícita e deve permanecer aberta até existir corroboração independente.',
    known_presence: '{platform}: presença pública observada em {url}',
    plan1: 'Valide links públicos autodeclarados dos achados de maior prioridade.',
    plan2: 'Resolva metadados públicos contraditórios antes de elevar a confiança de correlação.',
    plan3: 'Execute novamente apenas detectores inconclusivos após um intervalo quando a cobertura afetar materialmente a avaliação.',
    plan4: 'Pare de ampliar a coleta quando nova evidência não alterar mais os julgamentos principais nem fechar uma lacuna de inteligência.',
    stop: 'Pare de expandir a coleta quando nova evidência pública não alterar materialmente os julgamentos principais, resolver uma contradição ou fechar uma lacuna de inteligência.',
    sourceA: 'A = evidência pública direta/estável com forte suporte do detector e da observação.',
    sourceB: 'B = evidência forte de plataforma pública.',
    sourceC: 'C = evidência utilizável que ainda exige corroboração.',
    sourceD: 'D = observação fraca ou inconclusiva.',
    sourceE: 'E = sinal não verificado ou estruturalmente fraco.',
    sourceAI: 'Síntese de IA não pode elevar sozinha a confiança factual.',
  },
  es: {
    req_username_presence: 'Presencia de username',
    req_account_correlation: 'Correlación pública de cuentas',
    req_digital_footprint: 'Mapeo de huella digital',
    req_developer_footprint: 'Huella de desarrollo',
    req_threat_research_alias: 'Mapeo de alias para investigación de amenazas',
    req_brand_impersonation: 'Monitoreo de suplantación de marca',
    evidence_direct: 'El perfil público expone un enlace saliente independiente, que puede corroborar el hallazgo más allá de reutilizar el username.',
    evidence_lead: 'La presencia pública es un lead. Requiere corroboración independiente antes de cualquier conclusión de identidad.',
    evidence_inconclusive: 'El endpoint es inconcluso y no debe usarse como evidencia positiva de identidad.',
    pivot_direct: 'Valida el enlace público autodeclarado y compara si el mismo identificador público aparece de forma independiente en otro lugar.',
    pivot_metadata: 'Compara metadatos públicos y enlaces autodeclarados independientes antes de correlacionar este perfil con otra cuenta.',
    contradiction_display: 'Los nombres públicos mostrados difieren entre los perfiles observados.',
    contradiction_location: 'Los campos públicos de ubicación difieren entre los perfiles observados.',
    contradiction_org: 'Los campos públicos de organización difieren entre los perfiles observados.',
    contradiction_avatar: 'Los hashes públicos de avatar difieren entre los perfiles observados; la correlación visual de identidad debe reducirse hasta una resolución independiente.',
    contradiction_weak: '{count} resultado(s) positivo(s) dependen de un detector o una observación de baja confianza.',
    judgment_high: '{count} hallazgo(s) público(s) de alto valor son relevantes para {requirement}.',
    judgment_none: 'Ningún hallazgo de alto valor sustenta actualmente una conclusión analítica fuerte.',
    judgment_basis: 'Cobertura efectiva {coverage}%; {count} hallazgo(s) de alto valor.',
    judgment_cluster: '{category} es el cluster de huella observado más fuerte.',
    judgment_cluster_basis: '{count} hallazgos; score ponderado {score}/100.',
    judgment_gap: 'Las brechas de recolección limitan materialmente las conclusiones negativas.',
    judgment_gap_basis: '{count} resultado(s) están inciertos, rate-limited o con error.',
    gap1_q: '¿Qué conclusiones cambiarían si los servicios actualmente inconclusos estuvieran disponibles?',
    gap1_r: 'Solo {coverage}% de la recolección solicitada es concluyente.',
    gap2_q: '¿Existe un cross-link público independiente que conecte dos o más hallazgos?',
    gap2_r: 'La reutilización del mismo username, por sí sola, es insuficiente para una correlación fuerte entre cuentas.',
    gap3_q: '¿Puede elevarse algún hallazgo con una fuente pública más fuerte?',
    gap3_r: 'El conjunto actual de evidencia carece de suficientes fuentes de alta calidad.',
    pivot_contradiction_signal: '{count} señal(es) contradictoria(s)',
    pivot_contradiction_action: 'Resuelve metadatos públicos contradictorios antes de aumentar la confianza de correlación.',
    pivot_contradiction_reason: 'La evidencia contradictoria puede invalidar una hipótesis de correlación de cuentas aparentemente plausible.',
    pivot_collection_signal: '{count} respuesta(s) protegida(s) inconclusa(s)',
    pivot_collection_action: 'Vuelve a ejecutar más tarde solo los detectores inconclusos, con concurrencia conservadora.',
    pivot_collection_reason: 'Un reintento dirigido es más eficiente y menos ruidoso que repetir el escaneo completo.',
    timeline_found: 'Señal de perfil público observada durante este escaneo.',
    timeline_uncertain: 'Observación inconclusa durante este escaneo.',
    timeline_created: 'Timestamp público de creación de la cuenta informado por la fuente.',
    timeline_first: 'Timestamp de la primera evidencia pública registrado para este perfil.',
    timeline_source: 'Timestamp específico de observación informado por la fuente.',
    hypothesis_h1: 'Un subconjunto de hallazgos de alta confianza puede representar la misma identidad pública en línea.',
    hypothesis_h1_caveat: 'El mismo username es solo un lead; se requiere corroboración pública independiente.',
    hypothesis_h2: 'Los hallazgos dentro del cluster {category} pueden estar más relacionados entre sí que con hallazgos de otros clusters.',
    hypothesis_h2_caveat: 'La similitud de cluster refleja contexto observable del servicio, no una afirmación sobre identidad privada.',
    hypothesis_h3: 'Algunos hallazgos de menor confianza pueden ser colisiones de username no relacionadas.',
    hypothesis_h3_caveat: 'Esta es la hipótesis alternativa explícita y debe permanecer abierta hasta que exista corroboración independiente.',
    known_presence: '{platform}: presencia pública observada en {url}',
    plan1: 'Valida enlaces públicos autodeclarados de los hallazgos de mayor prioridad.',
    plan2: 'Resuelve metadatos públicos contradictorios antes de elevar la confianza de correlación.',
    plan3: 'Vuelve a ejecutar solo detectores inconclusos tras un intervalo cuando la cobertura afecte materialmente la evaluación.',
    plan4: 'Deja de ampliar la recolección cuando nueva evidencia ya no cambie los juicios principales ni cierre una brecha de inteligencia.',
    stop: 'Deja de ampliar la recolección cuando nueva evidencia pública ya no cambie materialmente los juicios principales, resuelva una contradicción o cierre una brecha de inteligencia.',
    sourceA: 'A = evidencia pública directa/estable con fuerte soporte del detector y la observación.',
    sourceB: 'B = evidencia fuerte de plataforma pública.',
    sourceC: 'C = evidencia utilizable que todavía requiere corroboración.',
    sourceD: 'D = observación débil o inconclusa.',
    sourceE: 'E = señal no verificada o estructuralmente débil.',
    sourceAI: 'La síntesis de IA no puede elevar por sí sola la confianza factual.',
  },
} as const;

type Key = keyof typeof messages.en;

function fmt(template: string, vars?: Record<string, string | number>) {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`));
}

export function analysisText(language: AnalysisLanguage, key: Key, vars?: Record<string, string | number>) {
  return fmt(messages[language][key], vars);
}

export function requirementLabel(language: AnalysisLanguage, requirement: string): string {
  const map: Record<string, Key> = {
    username_presence: 'req_username_presence',
    account_correlation: 'req_account_correlation',
    digital_footprint: 'req_digital_footprint',
    developer_footprint: 'req_developer_footprint',
    threat_research_alias: 'req_threat_research_alias',
    brand_impersonation: 'req_brand_impersonation',
  };
  return analysisText(language, map[requirement] || 'req_account_correlation');
}
